# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def aer2ecef(
    a: builtins.float,
    e: builtins.float,
    r: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts AER to an ECEF location

    # Arguments

    * `a` - Azimuth in degrees [f64]
    * `e` - Elevation in degrees [f64]
    * `r` - Range in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ecef` - Absolute ECEF position in meters
    """

def aer2ecef_uvw(
    a: builtins.float,
    e: builtins.float,
    r: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts AER to ECEF uvw

    # Arguments

    * `a` - Azimuth in degrees [f64]
    * `e` - Elevation in degrees [f64]
    * `r` - Range in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ecef_uvw` - Vector represented in ECEF frame. Not an absolute position [[meters]].
    """

def aer2enu(
    a: builtins.float, e: builtins.float, r: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts AER to ENU.

    # Arguments

    * `a` - Azimuth in degrees [f64]
    * `e` - Elevation in degrees [f64]
    * `r` - Range in meters [f64]

    # Returns

    * `enu` - Vector represented in ENU coordinates [meters].
    """

def aer2ned(
    a: builtins.float, e: builtins.float, r: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts AER to NED.

    # Arguments

    * `a` - Azimuth in degrees [f64]
    * `e` - Elevation in degrees [f64]
    * `r` - Range in meters [f64]

    # Returns

    * `ned` - Vector represented in NED coordinates [meters].
    """

def angle_between(
    ax: builtins.float,
    ay: builtins.float,
    az: builtins.float,
    bx: builtins.float,
    by: builtins.float,
    bz: builtins.float,
) -> builtins.float:
    r"""
    Computes the angle between two vectors in radians. Dot product is clamped to [-1, 1] so this always outputs a number

    # Arguments

    * `ax` - a vector x
    * `ay` - a vector y
    * `az` - a vector z
    * `bx` - b vector x
    * `by` - b vector y
    * `bz` - b vector z

    # Returns

    * `angle` - angle between the two vectors in radians
    """

def ecef2aer(
    x: builtins.float,
    y: builtins.float,
    z: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts an absolute ECEF to AER.

    # Arguments

    * `x` - ECEF x in meters [f64]
    * `y` - ECEF y in meters [f64]
    * `z` - ECEF z in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `aer` - Vector represented in AER coordinates [degrees-degrees-meters].
    """

def ecef2enu(
    x: builtins.float,
    y: builtins.float,
    z: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts an ECEF position to ENU.

    # Arguments

    * `x` - ECEF x in meters [f64]
    * `y` - ECEF y in meters [f64]
    * `z` - ECEF z in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `enu` - Vector represented in ENU coordinates [meters].
    """

def ecef2enu_dcm(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
]:
    r"""
    Calculates the direction cosine matrix that yields an ECEF to ENU transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `dcm` - ECEF to ENU direction cosine matrix [[xx, xy, xz], [yx, yy, yz], [zx, zy, zz]]
    """

def ecef2enu_quat(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
    r"""
    Calculates the quaternion that yields an ECEF to ENU transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `quat` - Normalized ECEF to ENU quaternion.
    """

def ecef2lla(
    x: builtins.float, y: builtins.float, z: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts ECEF to WGS84 LLA

    # Arguments

    * `x` - ECEF x in meters [f64]
    * `y` - ECEF y in meters [f64]
    * `z` - ECEF z in meters [f64]

    # Returns

    * `lla` - Vector represented in WGS84 LLA [degrees-degrees-meters].
    """

def ecef2ned(
    x: builtins.float,
    y: builtins.float,
    z: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts an absolute ECEF location to NED.

    # Arguments

    * `u` - ECEF u in meters [f64]
    * `v` - ECEF v in meters [f64]
    * `w` - ECEF w in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ned` - Vector represented in NED coordinates [meters].
    """

def ecef2ned_dcm(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
]:
    r"""
    Calculates the direction cosine matrix that yields an ECEF to NED transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `dcm` - ECEF to NED direction cosine matrix [[xx, xy, xz], [yx, yy, yz], [zx, zy, zz]]
    """

def ecef2ned_quat(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
    r"""
    Calculates the quaternion that yields an ECEF to NED transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `quat` - Normalized ECEF to NED quaternion (w, x, y, z).
    """

def ecef_quat2heading(
    w: builtins.float,
    x: builtins.float,
    y: builtins.float,
    z: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> builtins.float:
    r"""
    Computes the clockwise angle from North of a local body-frame's x-axis

    # Arguments

    * `w` - Scalar part of quaternion
    * `x` - x part of quaternion
    * `y` - y part of quaternion
    * `z` - z part of quaternion
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    *  `heading` - Clockwise angle off true north [[degrees]] of the body's x axis
    """

def ecef_uvw2aer(
    u: builtins.float,
    v: builtins.float,
    w: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts ECEF uvw to AER.

    # Arguments

    * `u` - ECEF u in meters [f64]
    * `v` - ECEF v in meters [f64]
    * `w` - ECEF w in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `aer` - Vector represented in AER coordinates [degrees-degrees-meters].
    """

def ecef_uvw2enu(
    u: builtins.float,
    v: builtins.float,
    w: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts an ECEF uvw vector to ENU.

    # Arguments

    * `u` - ECEF u in meters [f64]
    * `v` - ECEF v in meters [f64]
    * `w` - ECEF w in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `enu` - Vector represented in ENU coordinates [meters].
    """

def ecef_uvw2ned(
    u: builtins.float,
    v: builtins.float,
    w: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts ECEF UVW Vector to NED.

    # Arguments

    * `u` - ECEF u in meters [f64]
    * `v` - ECEF v in meters [f64]
    * `w` - ECEF w in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ned` - Vector represented in NED coordinates [meters].
    """

def enu2aer(
    e: builtins.float, n: builtins.float, u: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts ENU to AER.

    # Arguments

    * `e` - East in meters [f64]
    * `n` - North in meters [f64]
    * `u` - Up in meters [f64]

    # Returns

    * `aer` - Vector represented in AER coordinates [degrees-degrees-meters].
    """

def enu2ecef(
    e: builtins.float,
    n: builtins.float,
    u: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts ENU to an ECEF position

    # Arguments

    * `e` - East in meters [f64]
    * `n` - North in meters [f64]
    * `u` - Up in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ecef` - Absolute ECEF position in meters
    """

def enu2ecef_dcm(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
]:
    r"""
    Calculates the direction cosine matrix that yields an ENU to ECEF transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `dcm` - ENU to ECEF direction cosine matrix [[xx, xy, xz], [yx, yy, yz], [zx, zy, zz]]
    """

def enu2ecef_quat(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
    r"""
    Calculates the quaternion that yields an ENU to ECEF transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `quat` - Normalized ENU to ECEF quaternion (w, x, y, z).
    """

def enu2ecef_uvw(
    e: builtins.float,
    n: builtins.float,
    u: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts ENU to ECEF uvw vector

    # Arguments

    * `e` - East in meters [f64]
    * `n` - North in meters [f64]
    * `u` - Up in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ecef_uvw` - Vector represented in ECEF frame. Not an absolute position [[meters]].
    """

def enu2heading(
    e: builtins.float, n: builtins.float, u: builtins.float
) -> builtins.float:
    r"""
    Calculates heading angle from ENU.

    # Arguments

    * `e` - East in meters [f64]
    * `n` - North in meters [f64]
    * `u` - Up in meters [f64]

    # Returns

    * `heading_deg` - Heading angle relative to true north [degrees].
    """

def lla2ecef(
    lat_d: builtins.float, lon_d: builtins.float, alt_m: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts WGS84 LLA to ECEF.

    # Arguments

    * `lat_d` - WGS84 Lat in degrees
    * `lon_d` - WGS84 Lon in degrees
    * `alt_m` - WGS84 MSL alt in meters

    # Returns

    * `ecef` - Vector represented in ECEF coordinates [meters].
    """

def ned2aer(
    n: builtins.float, e: builtins.float, d: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts NED to AER.

    # Arguments

    * `n` - North in meters [f64]
    * `e` - East in meters [f64]
    * `d` - Down in meters [f64]

    # Returns

    * `aer` - Vector represented in AER coordinates [degrees-degrees-meters].
    """

def ned2ecef(
    n: builtins.float,
    e: builtins.float,
    d: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts NED to an absolute ECEF location

    # Arguments

    * `n` - North in meters [f64]
    * `e` - East in meters [f64]
    * `d` - Down in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ecef` - Absolute ECEF position in meters
    """

def ned2ecef_dcm(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
    builtins.float,
]:
    r"""
    Calculates the direction cosine matrix that yields an NED to ECEF transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `dcm` - NED to ECEF direction cosine matrix  [[xx, xy, xz], [yx, yy, yz], [zx, zy, zz]]
    """

def ned2ecef_quat(
    lat_d: builtins.float, lon_d: builtins.float
) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
    r"""
    Calculates the quaternion that yields an NED to ECEF transformation at this LLA.

    # Arguments

    * `lat_d` - Latitude reference [degrees].
    * `lon_d` - Longitude reference [degrees].

    # Returns

    * `quat` - Normalized NED to ECEF quaternion (w, x, y, z).
    """

def ned2ecef_uvw(
    n: builtins.float,
    e: builtins.float,
    d: builtins.float,
    lat_ref_d: builtins.float,
    lon_ref_d: builtins.float,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Converts NED to ECEF uvw

    # Arguments

    * `n` - North in meters [f64]
    * `e` - East in meters [f64]
    * `d` - Down in meters [f64]
    * `lat_ref_d` - Reference WGS84 Lat in degrees
    * `lon_ref_d` - Reference WGS84 Lon in degrees

    # Returns

    * `ecef_uvw` - Vector represented in ECEF frame. Not an absolute position [[meters]].
    """

def rand_ecef() -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Generates a uniform random ECEF point on the surface of a spherical Earth.

    # Returns

    * `ecef` - Random ECEF location [meters].
    """

def rand_lla() -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Generates a uniform random LLA point. Altitude is generated in the domain [0.0, 10000.0].

    # Returns

    * `lla` - Random LLA location [degrees-degrees-meters].
    """

def rand_orientation() -> tuple[
    builtins.float, builtins.float, builtins.float, builtins.float
]:
    r"""
    Generates a random normalized quaternion.

    # Returns

    * `quat` - Random normalized quaternion (w, x, y, z).
    """

def vincenty_direct(
    lat_d: builtins.float,
    long_d: builtins.float,
    range_m: builtins.float,
    bearing_deg: builtins.float,
    atol: builtins.float,
    max_iters: builtins.int,
) -> tuple[builtins.float, builtins.float]:
    r"""
    Calculates the LLA location that is a fixed range and bearing from a reference LLA. This function uses an iterative
    solution to determine outputs using the WGS84 ellipsoidal Earth model.

    See reference:
    https://en.wikipedia.org/wiki/Vincenty%27s_formulae.

    # Arguments

    * `lat_deg` - Latitude reference [degrees].
    * `lon_deg` - Longitude reference [degrees].
    * `range_m` - Range (i.e., distance) from point A to point B [meters].
    * `bearing_deg` - Bearing (i.e., azimuth) from point A to point B relative to true north [degrees].
    * `abs_tol` - Absolute tolerance used for convergence.
    * `max_iters` - Maximum possible number of iterations before early termination.

    # Returns

    A tuple `(lat_deg, lon_deg)` where:
    * `lat_deg` - Latitude location [degrees].
    * `lon_deg` - Longitude location [degrees].
    """

def vincenty_inverse(
    lat_a_deg: builtins.float,
    lon_a_deg: builtins.float,
    lat_b_deg: builtins.float,
    lon_b_deg: builtins.float,
    atol: builtins.float,
    max_iters: builtins.int,
) -> tuple[builtins.float, builtins.float, builtins.float]:
    r"""
    Calculates range and bearings between two latitude-longitude points. This function uses an iterative solution to
    determine outputs using the WGS84 ellipsoidal Earth model.

    See reference:
    https://en.wikipedia.org/wiki/Vincenty%27s_formulae.

    # Arguments

    * `lat_a_deg` - Latitude point A [degrees].
    * `lon_a_deg` - Longitude point A [degrees].
    * `lat_b_deg` - Latitude point A [degrees].
    * `lon_b_deg` - Longitude point A [degrees].
    * `atol` - Absolute tolerance used for convergence.
    * `max_iters` - Maximum possible number of iterations before early termination.

    # Returns

    A tuple `(range_m, bearing_ab_deg, bearing_ba_deg)` where:
    * `range_m` - Range (i.e., distance) from point A to point B [meters].
    * `bearing_ab_deg` - Bearing (i.e., azimuth) from point A to point B relative to true north [degrees].
    * `bearing_ba_deg` - Bearing (i.e., azimuth) from point B to point A relative to true north [degrees].
    """
