[package]
name = "map3d"
description = "Geodetic coordinate conversion library"
keywords = ["geodetic", "engineering", "scientific", "gis"]
license-file = "../../LICENSE"
homepage = "https://github.com/lskyweiler/rustmap3d"
repository = "https://github.com/lskyweiler/rustmap3d"
readme = "README.md"
version.workspace = true
edition.workspace = true

[dependencies]
glam.workspace = true
almost = "~0.2"
rand = "~0.9"
chrono = "~0.4"
approx = "~0.5"
rand_distr = "0.5.1"

either.workspace = true
pyo3 = { workspace = true, optional = true }
pyo3-stub-gen = { workspace = true, optional = true }

# simple-py-bevy = { "git" = "https://github.com/lskyweiler/simple-py-bevy", optional = true }
# pyglam = { git = "https://github.com/lskyweiler/pyglam", branch = "feat/py-bevy" }
simple-py-bevy = { path = "C:\\DEC\\am\\projects\\simple-py-bevy", optional = true }
pyglam = { path = "C:\\DEC\\am\\projects\\pyglam", default-features = false }

bevy = { workspace = true, optional = true }
serde = { version = "~1.0", features = ["derive"], optional = true }

map3d_derive = { path = "../map3d_derive" }

[dev-dependencies]
rstest = "0.26"
criterion = { version = "~0.8", features = ["html_reports"] }

[[bench]]
name = "geobench"
harness = false

[features]
# generate pyo3 functions at all
pyo3 = ["dep:pyo3", "dep:pyo3-stub-gen", "pyglam/pyo3"]
# only bevy functionality
bevy = ["dep:bevy", "dep:serde", "pyglam/bevy"]
# bevy and py ref functionality
py-bevy = [
    "pyo3",
    "bevy",
    "dep:simple-py-bevy",
    "simple-py-bevy/py-bevy",
    "simple-py-bevy/py-ref",
    "pyglam/py-ref",
]
