vec3tuple = tuple[float, float, float]  # [x, y, z]
quattuple = tuple[float, float, float, float]  # [w, i, j, k]
mat3tuple = tuple[
    float, float, float, float, float, float, float, float, float
]  # column major 3x3 matrix. column major per glm convention

def aer2ecef(
    az: float, el: float, range: float, ref_lat_deg: float, ref_lon_deg: float, ref_alt: float
) -> vec3tuple: ...
def aer2enu(az: float, el: float, range: float) -> vec3tuple: ...
def aer2ned(az: float, el: float, range: float) -> vec3tuple: ...
def angle_between(a: vec3tuple, b: vec3tuple) -> float: ...
def ecef2aer(
    x: float, y: float, z: float, ref_lat_deg: float, ref_lon_deg: float
) -> vec3tuple: ...
def ecef2bearing(
    x: float, y: float, z: float, ref_lat_deg: float, ref_lon_deg: float
) -> float: ...
def ecef2enu(
    x: float, y: float, z: float, ref_lat_deg: float, ref_lon_deg: float
) -> vec3tuple: ...
def ecef2enu_dcm(lat_deg: float, lon_deg: float) -> mat3tuple: ...
def ecef2enu_quat(lat_deg: float, lon_deg: float) -> quattuple: ...
def ecef2lla(x: float, y: float, z: float) -> vec3tuple: ...
def ecef2ned(
    x: float, y: float, z: float, ref_lat_deg: float, ref_lon_deg: float
) -> vec3tuple: ...
def ecef2ned_dcm(lat_deg: float, lon_deg: float) -> mat3tuple: ...
def ecef2ned_quat(lat_deg: float, lon_deg: float) -> quattuple: ...
def enu2aer(east: float, north: float, up: float) -> vec3tuple: ...
def enu2ecef(
    east: float, north: float, up: float, ref_lat_deg: float, ref_lon_deg: float
) -> vec3tuple: ...
def enu2ecef_dcm(lat_deg: float, lon_deg: float) -> mat3tuple: ...
def enu2ecef_quat(lat_deg: float, lon_deg: float) -> quattuple: ...
def lla2ecef(lat_deg: float, lon_deg: float, alt: float) -> vec3tuple: ...
def ned2aer(north: float, east: float, down: float) -> vec3tuple: ...
def ned2ecef(
    north: float, east: float, down: float, ref_lat_deg: float, ref_lon_deg: float
) -> vec3tuple: ...
def ned2ecef_dcm(lat_deg: float, lon_deg: float) -> mat3tuple: ...
def ned2ecef_quat(lat_deg: float, lon_deg: float) -> quattuple: ...
def orient_ecef_quat_towards_lla(
    obs_ecef: vec3tuple, obs_ecef_quat: vec3tuple, target_ecef: vec3tuple
) -> quattuple: ...
def rand_ecef() -> vec3tuple: ...
def rand_lla() -> vec3tuple: ...
def rand_orientation() -> quattuple: ...
